# Default config location
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  FinalNewline:
    active: false
  NoWildcardImports:
    active: false


style:
  NewLineAtEndOfFile:
    active: false
  WildcardImport:
    active: false
  MagicNumber:
    active: false